---
# Non-sensitive MySQL variables
mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_ivolve_user: "{{ vault_mysql_ivolve_user }}"
mysql_ivolve_password: "{{ vault_mysql_ivolve_password }}"

mysql_ivolve_db: "iVolve"
mysql_bind_address: "0.0.0.0"
mysql_port: 3306
