$ANSIBLE_VAULT;1.1;AES256
39616333383830626132306461386665663261323837386561306235343332613835663733633132
6137633836613638313637633539653561306665663537360a303630306662383532323437353762
37343563353031336362393934666130353161313762613862636166363238313235396633306535
6535656662323966380a633039613437326137373162386630356166373262396535626430303162
62623734613732626535666664346138386564363536383063353236366263613161623564333935
35353063363434316366616564623434653934333732303661323463646566376331346463613766
65633065356436393933306162343839343832316336356233313430343831623761333462636263
38393662336133633031656239636662356435373738366331316163623533666137636432376163
39376664323139333235303139393831636561303366633065393366663337613564653265623037
36376132376333323361303630623939383564623837303533393936613438386238323164363566
32363464623039336132336332393037663936343465353163383562633134393065326133383839
36393561653234653334
