apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-config
  namespace: ivolve
data:
  APP_NAME: "iVolve Node.js Application"
  APP_VERSION: "1.0.0"
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "mysql-headless"
  DB_NAME: "ivolve"
