apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: ivolve
data:
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_ROOT_USER: "root"
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DB: "ivolve"
  MYSQL_USER: "ivolve_user"
  MYSQL_PASSWORD: "ivolve_pass"
