apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-config
data:
  DB_HOST: mysql-headless
  DB_USER: root
  DB_PASSWORD: password123456
  DB_NAME: ivolve
  DB_USER_NEW: ivolve_user
  DB_USER_PASS: ivolve_pass
  PORT: "3000"

