apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-service
  labels:
    app: jenkins-app
spec:
  type: LoadBalancer
  selector:
    app: jenkins-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: http
