$ANSIBLE_VAULT;1.1;AES256
34313461616162313462376331636266323464646663663838376266353831376261386564353961
6531386366613364623762303135653738633733366365390a393938313232373537323631303131
64363934393036646632316461653866613633326430373030336632383231623864383331336166
6636333764623163390a303134316231353330356236363630366665656338383662643632326565
66633366376335643138313534636237343335643132336561363632333734653238633065303837
66373835343538363766613330313564636631636334356231346364353237643430373534376235
31396438303064626635316337353531313863343362633433656335353332663537653639383637
66343430643164616134313365313664616438656136643330653936383036623864623339636134
36376334373862633937313336623739313862333136383135383365323766663932
